### PR TITLE
Add required loading state to button

### PR DESCRIPTION
**Pull request by abgeorge7**
A lot of times our buttons provide an action that calls and API - we should show a spinner and disable them in this scenario. 

Added to the storybook for testing :)

### CODE REVIEW

**Comment by qingyashu** [comment]
Awesome! it works well! just my thoughts: how about just let `isPending` state to optional props and set default value to `false`?

**Comment by abgeorge7** [comment]
updated 👍

**Review by qingyashu — APPROVED** [review]
👍  LGTM!

**Comment by zflamig** [comment]
Should we include something in the onclick here that checks the current loading state by default too to encourage that?

**Pull request merged**
