### PR TITLE
Feat/dropdown enhancements: Give dropdown support for rightIcon attribute

### PR DESCRIPTION
**Pull request by ZakirG**

### CODE REVIEW

**Review by qingyashu — COMMENTED** [review]
Would be nice to add example in storybook, also version need to be change to 0.2.2

**Comment by ZakirG** [comment]
> Would be nice to add example in storybook, also version need to be change to 0.2.2

**Comment by ZakirG** [comment]
Ok added a story and changed the version 😊

**Review by qingyashu — APPROVED** [review]
Awesome~

**Pull request merged**
